detection/urls.py
from django.conf.urls import url
from . import views, auth_views

urlpatterns = [
    url(
        r'^(?P<panel_id>[0-9]+)/user_query/(?P<url>[_A-Za-z]+)$',
        views.user_query,
        name='user_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/gang_query/(?P<url>[_A-Za-z]+)$',
        views.gang_query,
        name='gang_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/gang_detail_query/(?P<url>[_A-Za-z]+)$',
        views.gang_detail_query,
        name='gang_detail_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/deal_query/(?P<url>[_A-Za-z]+)$',
        views.deal_query,
        name='deal_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/everyday_deal_query/(?P<url>[_A-Za-z]+)$',
        views.everyday_deal_query,
        name='everyday_deal_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/history_query/(?P<url>[_A-Za-z]+)$',
        views.history_query,
        name='history_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/ban_query/(?P<url>[_A-Za-z]+)$',
        views.ban_query,
        name='ban_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/bind_account/(?P<url>[_A-Za-z]+)$',
        views.bind_account,
        name='bind_account'),
    url(
        r'^(?P<panel_id>[0-9]+)/everyday_history_query/(?P<url>[_A-Za-z]+)$',
        views.everyday_history_query,
        name='everyday_history_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/chat_query/(?P<url>[_A-Za-z]+)$',
        views.chat_query,
        name='chat_query'),
    url(
        r'^(?P<panel_id>[0-9]+)/(?P<t_p>[_A-Za-z]+)/(?P<url>[_A-Za-z]+).json$',
        views.json_template,
        name='json_template'),
    url(
        r'^(?P<panel_id>[0-9]+)/count/(?P<url>[_A-Za-z]+)$',
        views.count,
        name='count'),
    url(
        r'^(?P<panel_id>[0-9]+)/count_with_pay_channel/(?P<url>[_A-Za-z]+)$',
        views.count_with_pay_channel,
        name='count_with_pay_channel'),
    url(
        r'^(?P<panel_id>[0-9]+)/count_without_time/(?P<url>[_A-Za-z]+)$',
        views.count_without_time,
        name='count_without_time'),
    url(
        r'^(?P<panel_id>[0-9]+)/count_only_time/(?P<url>[_A-Za-z]+)$',
        views.count_only_time,
        name='count_only_time'),
    url(
        r'^(?P<panel_id>[0-9]+)/online/(?P<url>[_A-Za-z]+)$',
        views.online,
        name='online'),
    url(r'^$', auth_views.index, name='default_index'),
]

guardmaster/urls.py
from django.views.i18n import javascript_catalog
from django.conf.urls import include, url
from django.contrib import admin
from detection import auth_views
js_info_dict = {
    'packages': ('detection',),
}
urlpatterns = [
    # Examples:
    # url(r'^$', 'guardmaster.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^detection/', include('detection.urls', namespace='detection')),
    url(r'^operating/', include('operating.urls', namespace='operating')),
    url(r'^deployment/', include('deployment.urls', namespace='deployment')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', auth_views.index, name='index'),
    url(r'^login/$', auth_views.user_login, name='user_login'),
    url(r'^logout/$', auth_views.user_logout, name='user_logout'),
]

operating/urls.py
from django.conf.urls import url
from . import views
from detection import auth_views
from detection import views as detection_views

urlpatterns = [
    url(
        r'^(?P<panel_id>[0-9]+)/(?P<t_p>[_A-Za-z]+)/(?P<url>[_A-Za-z]+).json$',
        detection_views.json_template,
        name='json_template'),
    url(
        r'^(?P<panel_id>[0-9]+)/notify/(?P<url>[_A-Za-z]+)$',
        views.notify,
        name='notify'),
    url(
        r'^(?P<panel_id>[0-9]+)/notify/(?P<id>[0-9]+)$',
        views.edit_notify,
        name='edit_notify'),
    url(
        r'^(?P<panel_id>[0-9]+)/mail/(?P<url>[_A-Za-z]+)$',
        views.mail,
        name='mail'),
    url(
        r'^(?P<panel_id>[0-9]+)/all_mail/(?P<url>[_A-Za-z]+)$',
        views.all_mail,
        name='all_mail'),
    url(
        r'^(?P<panel_id>[0-9]+)/rank/(?P<url>[_A-Za-z]+)$',
        views.rank,
        name='rank'),
    url(
        r'^(?P<panel_id>[0-9]+)/single/(?P<url>[_A-Za-z]+)$',
        views.single,
        name='single'),
    url(
        r'^(?P<panel_id>[0-9]+)/single/(?P<url>[_A-Za-z]+)/(?P<type>[_0-9a-zA-Z]+).json$',
        views.change_single,
        name='change_single'),
    url(
        r'^(?P<panel_id>[0-9]+)/contact/(?P<url>[_A-Za-z]+)$',
        views.contact,
        name='contact'),
    url(
        r'^(?P<panel_id>[0-9]+)/contact/(?P<issue_id>[0-9]+)$',
        views.contact_reply,
        name='contact_reply'),
    url(
        r'^(?P<panel_id>[0-9]+)/contact/(?P<issue_id>[0-9]+).json$',
        views.contact_status,
        name='contact_status'),
    url(
        r'^(?P<panel_id>[0-9]+)/guard_master_order/(?P<url>[_A-Za-z]+)$',
        views.guard_master_order,
        name='guard_master_order'),
    url(r'^$', auth_views.index, name='default_index'),
]

operating/views.py
from detection.models import Excuse, Panel, UISubMenu, UIMainMenu, Tabel
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _
from operating.servercontrol import ServerControl
from operating.notifydeployment import NotifyDeployment
from detection.value_format import ValueFormat
from detection.views import view_template
from guardmaster import common as Common
from operating.models import *
from pprint import pprint
import json
import time


def enum_equip_list(panel_id):
    if Common.E_EQUIPID_LIST is None:
        tmp_list = Tabel.get_enum(panel_id, Common.E_EQUIPID)
        tmp_list = map(lambda x: {
            'EnumCd': int(x['EnumCd']), 'EnumDes': x['EnumDes']}, tmp_list)
        tmp_list = sorted(tmp_list, key=lambda x: x['EnumCd'])
        tmp_list = map(lambda x: {
            'EnumCd': str(x['EnumCd']), 'EnumDes': x['EnumDes']}, tmp_list)
        Common.E_EQUIPID_LIST = tmp_list
    return Common.E_EQUIPID_LIST


def enum_item_list(panel_id):
    if Common.E_ITEMNAME_LIST is None:
        tmp_list = Tabel.get_enum(panel_id, Common.E_ITEMNAME)
        tmp_list = map(lambda x: {
            'EnumCd': int(x['EnumCd']), 'EnumDes': x['EnumDes']}, tmp_list)
        tmp_list = sorted(tmp_list, key=lambda x: x['EnumCd'])
        tmp_list = map(lambda x: {
            'EnumCd': str(x['EnumCd']), 'EnumDes': x['EnumDes']}, tmp_list)
        Common.E_ITEMNAME_LIST = tmp_list
    return Common.E_ITEMNAME_LIST


def enum_factor_list(panel_id):
    if Common.E_FACTOR_LIST is None:
        tmp_list = Tabel.get_enum(panel_id, Common.E_FACTOR)
        tmp_list = map(lambda x: {
            'EnumCd': int(x['EnumCd']), 'EnumDes': x['EnumDes']}, tmp_list)
        tmp_list = sorted(tmp_list, key=lambda x: x['EnumCd'])
        tmp_list = map(lambda x: {
            'EnumCd': str(x['EnumCd']), 'EnumDes': x['EnumDes']}, tmp_list)
        Common.E_FACTOR_LIST = tmp_list
    return Common.E_FACTOR_LIST


def enum_package_channel_list(panel_id):
    if Common.E_PACKAGECHANNEL_LIST is None:
        Common.E_PACKAGECHANNEL_LIST = Tabel.get_enum(
            panel_id, Common.E_PACKAGECHANNEL)
    return Common.E_PACKAGECHANNEL_LIST


@Common.competence_required
def notify(request, panel_id, url=Common.URL):
    if 'synchronization' in request.POST:
        t = "operating/synchronization.html"
        d = view_template(request, panel_id, url)
        nd = NotifyDeployment(panel_id, request.user.username)
        d['cdn_urls'] = nd.tojson()
        return render(request, t, d)
    t = "operating/notify.html"
    d = view_template(request, panel_id, url)
    panel = get_object_or_404(Panel, pk=panel_id)
    d['servers'] = panel.server_set.filter(server_type='dir')
    d['notifys'] = panel.notify_set.all()
    d['channels'] = enum_package_channel_list(panel_id)
    d['url'] = url
    if request.method == 'POST':
        nd = NotifyDeployment(panel_id, request.user.username)
        ret = nd.add(request.POST)
        d['message'] = ret
    return render(request, t, d)


@Common.competence_required
def edit_notify(request, panel_id, id):
    if request.method == 'GET':
        t = "operating/notify.html"
        url = 'notify'
        d = view_template(request, panel_id, url)
        panel = get_object_or_404(Panel, pk=panel_id)
        notify = get_object_or_404(Notify, pk=id)
        d['servers'] = panel.server_set.filter(server_type='dir')
        d['notifys'] = panel.notify_set.all()
        d['channels'] = enum_package_channel_list(panel_id)
        d['url'] = url
        notify.start = Common.datetime2string(notify.start, 28800)
        notify.end = Common.datetime2string(notify.end, 28800)
        d['notify'] = notify
        return render(request, t, d)
    if request.method == 'POST':
        notify = get_object_or_404(Notify, pk=id)
        notify.delete()
        ret = 0
        ret = {'result': ret}
        ret = json.dumps(ret, ensure_ascii=False)
        return HttpResponse(ret, content_type='application/json')


@Common.competence_required
def mail(request, panel_id, url=Common.URL):
    t = "operating/mail.html"
    d = view_template(request, panel_id, url)
    panel = get_object_or_404(Panel, pk=panel_id)
    d['servers'] = panel.server_set.filter(server_type='dir')
    d['equips'] = enum_equip_list(panel_id)
    d['items'] = enum_item_list(panel_id)
    d['factors'] = enum_factor_list(panel_id)
    d['responsemails'] = Common.get_panel_response_mail(panel)
    d['url'] = url
    if request.GET.get('result'):
        d['message'] = request.GET.get('result')
    if request.method == 'POST':
        server_id = int(request.POST['server'])
        try:
            u = request.POST['uid'].split(',')
            u = map(lambda x: int(x), u)
            if len(u) == 1:
                uid = u[0]
            if len(u) > 1 and len(u) <= 1000:
                uid = u
            if len(u) > 1000:
                d['message'] = 2
                return render(request, t, d)
        except Exception as e:
            d['message'] = 2
            return render(request, t, d)

        server = get_object_or_404(Server, pk=server_id)
        sc = ServerControl(
            server,
            uid,
            panel_id,
            request.user.username,
            Common.get_client_ip(request))
        ret = sc.send_mail(post=request.POST)
        hrrurl = reverse('operating:mail', args=(panel_id, url)) + '?result=' + str(ret['result'])
        return HttpResponseRedirect(hrrurl)
    return render(request, t, d)


@Common.competence_required
def all_mail(request, panel_id, url=Common.URL):
    t = "operating/all_mail.html"
    d = view_template(request, panel_id, url)
    panel = get_object_or_404(Panel, pk=panel_id)
    d['servers'] = panel.server_set.filter(server_type='dir')
    d['equips'] = enum_equip_list(panel_id)
    d['items'] = enum_item_list(panel_id)
    d['factors'] = enum_factor_list(panel_id)
    d['responseallmails'] = Common.get_panel_response_all_mail(panel)
    if request.GET.get('result'):
        d['message'] = request.GET.get('result')
    if request.method == 'POST':
        server_id = int(request.POST['server'])

        server = get_object_or_404(Server, pk=server_id)
        sc = ServerControl(
            server,
            0,
            panel_id,
            request.user.username,
            Common.get_client_ip(request))
        ret = sc.send_all_mail(request.POST)
        hrrurl = reverse('operating:all_mail', args=(panel_id, url)) + '?result=' + str(ret['result'])
        return HttpResponseRedirect(hrrurl)
    return render(request, t, d)


@Common.competence_required
def single(request, panel_id, url=Common.URL):
    t = "operating/single.html"
    d = view_template(request, panel_id, url)
    panel = get_object_or_404(Panel, pk=panel_id)
    d['servers'] = panel.server_set.filter(server_type='dir')
    d['url'] = url
    if request.method == 'POST':
        server_id = int(request.POST['server'])
        uid = int(request.POST['uid'])
        server = get_object_or_404(Server, pk=server_id)
        sc = ServerControl(
            server,
            uid,
            panel_id,
            request.user.username,
            Common.get_client_ip(request))
        if url == 'single_query_tw':
            ret = sc.base_info_tw()
        else:
            ret = sc.base_info()
        d['player'] = ret
        d['server_id'] = server_id
        d['uid'] = uid
    return render(request, t, d)


@Common.competence_required
def contact(request, panel_id, url=Common.URL):
    t = "operating/contact.html"
    d = view_template(request, panel_id, url)
    panel = get_object_or_404(Panel, pk=panel_id)
    d['servers'] = panel.server_set.filter(server_type='dir')
    return render(request, t, d)


@Common.competence_required
def contact_reply(request, panel_id, issue_id):
    url = 'contact'
    t = "operating/contact.html"
    d = view_template(request, panel_id, url)
    panel = get_object_or_404(Panel, pk=panel_id)
    sub_menu = Common.get_user_sub_menu(request.user, url)
    d['servers'] = panel.server_set.filter(server_type='dir')
    issue = Tabel.contact_select(sub_menu, panel, {'id': issue_id})
    if not issue:
        return HttpResponseRedirect('/')
    v = ValueFormat(sub_menu.get_col_map_vals('col_type'), panel_id)
    issue = Common.kvs(sub_menu.get_col_map_vals('col_name'), v.execute(issue))
    issue = Common.first(issue)
    d['issue'] = issue
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        server = get_object_or_404(Server, hostname=issue['hostname'], panel=panel)
        if title and len(title) < 30 and content and len(content) < 256:
            sc = ServerControl(
                server,
                int(issue['uid']),
                panel_id,
                request.user.username,
                Common.get_client_ip(request))
            ret = sc.send_mail(title, content)
            vals = (
                issue_id,
                title,
                content,
                Common.now(),
                request.user.username,
                str(Common.first(ret['sucess_result'])['mail_id'])
            )
            if ret['result'] == 0:
                Tabel.contact_insert(panel, vals)
                Tabel.update_contact_status(panel, 1, issue_id)
    reply = Tabel.contact_reply_select(panel, issue_id)
    d['reply'] = reply
    return render(request, t, d)


@Common.competence_required
def contact_status(request, panel_id, issue_id):
    panel = get_object_or_404(Panel, pk=panel_id)
    Tabel.update_contact_status(panel, 2, issue_id)
    ret = 0
    ret = {'result': ret}
    ret = json.dumps(ret, ensure_ascii=False)
    return HttpResponse(ret, content_type='application/json')

operating/templates/operating/contact.html
{% extends "detection/base.html" %}
{% block content %}
{% load custom i18n %}
{% trans "Issue Info" as t_issue_info %}
{% trans "Issue ID" as t_issue_id %}
{% trans "Uid" as t_uid %}
{% trans "Uin" as t_uin %}
{% trans "Name" as t_name %}
{% trans "Hostname" as t_hostname %}
{% trans "Channel ID" as t_channel_id %}
{% trans "Platform" as t_platform %}
{% trans "Version" as t_version %}
{% trans "Issue Type" as t_issue_type %}
{% trans "Issue Time" as t_issue_time %}
{% trans "Issue Content" as t_issue_content %}
{% trans "History Reply" as t_history_reply %}
{% trans "Reply Mail" as t_reply_mail %}
{% trans "Mail Title" as t_mail_title %}
{% trans "Mail Content" as t_mail_content %}
{% trans "4 Words Limited" as t_4_words_limited %}
{% trans "120 Words Limited" as t_120_words_limited %}
{% trans "Reply" as t_reply %}
{% trans "Return List" as t_return_list %}
<div class="container-fluid white-bg">
  {% if issue %}
  <ol class="breadcrumb">
    <li><a href="{{servlet}}/">{{panel.label}}</a></li>
    <li class="active">{{ title }}</li>
  </ol>
  <div class="panel panel-primary">
    <div class="panel-heading">{{ t_issue_info }}</div>
    <!-- Table -->
    <table class="table table-striped">
      <tbody>
        <tr>
          <td><b>{{ t_issue_id }}</b></td>
          <td>{{ issue.issueid }}</td>
          <td><b>{{ t_uid }}</b></td>
          <td>{{ issue.uid }}</td>
        </tr>
        <tr>
          <td><b>{{ t_uin }}</b></td>
          <td>{{ issue.uin }}</td>
          <td><b>{{ t_name }}</b></td>
          <td>{{ issue.name }}</td>
        </tr>
        <tr>
          <td><b>{{ t_hostname }}</b></td>
          <td>{{ issue.hostname }}</td>
          <td><b>{{ t_channel_id }}</b></td>
          <td>{{ issue.channelid }}</td>
        </tr>
        <tr>
          <td><b>{{ t_platform }}</b></td>
          <td>{{ issue.platform }}</td>
          <td><b>{{ t_version }}</b></td>
          <td>{{ issue.version }}</td>
        </tr>
        <tr>
          <td><b>{{ t_issue_type }}</b></td>
          <td>{{ issue.issuetype }}</td>
          <td><b>{{ t_issue_time }}</b></td>
          <td>{{ issue.opentime }}</td>
        </tr>
        <tr>
          <td><b>{{ t_issue_content }}</b></td>
          <td colspan="3"><p class="text-danger">{{ issue.issuecontent }}<p></td>
        </tr>
      </tbody>
    </table>
    <ul class="list-group">
      <li class="list-group-item"><b>{{ t_history_reply }}</b></li>
      {% for r in reply %}
      <li class="list-group-item">
        <span>{{ r.title }}</span>
        <span class="label label-info">{{ r.updateoper }}</span>
        <span class="label label-default">{{ r.updatetime }}</span>
      </li>
      <li class="list-group-item"><p class="text-success">&emsp;&emsp;{{ r.content }}</p></li>
      {% endfor %}
    </ul>
    <ul class="list-group">
      <li class="list-group-item"><b>{{ t_reply_mail }}</b></li>
      <li class="list-group-item">
        <form class="form" role="form" method="post">
        {% csrf_token %}
          <div class="form-group">
            <label for="title">{{ t_mail_title }}</label>&emsp;<span class="label label-danger">{{ t_4_words_limited }}</span>
            <input type="text" class="form-control" id="title" name="title">
          </div>
          <div class="form-group">
            <label for="content">{{ t_mail_content }}</label>&emsp;<span class="label label-danger">{{ t_120_words_limited }}</span>
            <input type="text" class="form-control" id="content" name="content">
          </div>
          <button type="submit" class="btn btn-primary btn-sm" onclick="return queryButton.mailConfirm()">{{t_reply}}</button>
          <a href="{% url 'operating:contact' panel.id 'contact' %}">{{t_return_list}}</a>
        </form>
      </li>
    </ul>
  </div>
  {% else %}
  <script type="text/javascript">
   $(document).ready(function() {
     $('.input-datepicker').datepicker({
       format: "yyyy-mm-dd",
       weekStart: 0,
       language: gettext('en'),
       autoclose: true,
       todayHighlight: true
     });
   });
  </script>
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="{{servlet}}/">{{panel.label}}</a></li>
      <li class="active">{{ title }}</li>
    </ol>
    <form class="form" role="form" id="contactForm">
      <div class="form-group" style="margin-bottom:5px">
        <label>{{ t_range_of_date }}</label>
        <div class="input-daterange input-group input-datepicker" id="datepicker">
          <input type="text" class="input-md form-control" name="start">
          <span class="input-group-addon">{{ t_to }}</span>
          <input type="text" class="input-md form-control" name="end">
        </div>
      </div>
      <div class="form-group" style="margin-bottom:5px">
        <label>{{t_list_of_servers}}</label>
        <select class="form-control" name="hostname">
          {% for server in servers %}
          <option value="{{server.hostname}}">{{server.label}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group" style="margin-bottom: 5px">
          <label for="uid">{{t_uid}}</label>
            <input type="text" class="form-control" id="uid" name="uid">
      </div>

      <button type="submit" class="btn btn-default btn-sm" id="count-button"onclick="return dataAccess.contactJSON()">{{t_query}}</button>
    </form>

    <p class="sub-header"></p>
    <div class="table-responsive">
      <table class="table table-bordered table-striped" id="sources">
    <thead>
      <tr>
        {% for table in table_head %}
        <th>{{table.label}}</th>
        {% endfor %}
      </tr>
    </thead>
      </table>
    </div>
  </div>
  {% endif %}
  <center style='color: #999; padding-top: 20px; font-family: "arial","NSimSun","SimSun","STSong","AR PL SungtiL GB","TW\-Sung","WenQuanYi Bitmap Song"; font-size: 14px; font-weight: bold;'>{{excuse}}</center>
</div>
<script type="text/javascript">
 $(document).ready(function() {
   queryButton.initDate('{{count_date.start}}', '{{count_date.end}}');
 });
</script>
{% endblock %}

operating/templates/operating/rank.html
{% extends "detection/base.html" %}
{% block content %}
{% load custom i18n %}
{% trans "Real Rank Info" as t_real_rank_info %}
{% trans "Rank List" as t_rank_list %}
{% trans "Range Of Rank" as t_range_of_rank %}
{% trans "Max Range In 100" as t_max_range_in_100 %}
{% trans "Total Number" as t_total_number %}
{% trans "Rank Pos" as t_rank_pos %}
{% trans "Player ID" as t_player_id %}
{% trans "Player Name" as t_player_name %}
{% trans "Is Robot" as t_is_robot %}
{% trans "Recharge ID" as t_recharge_id %}
{% trans "Gang ID" as t_gang_id %}
{% trans "Gang Name" as t_gang_name %}
{% trans "Gang Level" as t_gang_level %}
<div class="container-fluid white-bg">
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="{{servlet}}/">{{panel.label}}</a></li>
      <li class="active">{{ title }}</li>
    </ol>
    <form class="form" role="form"  method="post" action="{% url 'operating:rank' panel.id 'all_rank' %}">
      {% csrf_token %}
      <div class="form-group" style="margin-bottom: 5px">
        <label>{{t_list_of_servers}}</label>
        <select class="form-control" name="server">
          {% for server in servers %}
          <option value="{{server.id}}" {% ifequal server_id server.id %}selected{% endifequal %}>{{server.label}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group" style="margin-bottom: 5px">
        <label>{{t_rank_list}}</label>
        <select class="form-control" name="rank">
          {% for rank in ranks %}
          <option value="{{rank.id}}" {% ifequal rank_id rank.id %}selected{% endifequal %}>{{rank.label}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group" style="margin-bottom: 5px">
        <label>{{t_zone}}</label>
        <select class="form-control" name="zone">
          {% for zone in zones %}
          {% if zone.EnumCd != '0' %}
          <option value="{{zone.EnumCd}}" {% ifequal notify.world_id zone.EnumCd %}selected{% endifequal %}>{{zone.EnumDes}}</option>
          {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="form-group" style="margin-bottom:5px">
        <label>{{t_range_of_rank}}&emsp;<span class="label label-danger">{{ t_max_range_in_100 }}</span></label>
        <div class="input-daterange input-group">
          <input type="text" class="input-md form-control" name="rank_start" value="{{ rank_start|default:1 }}">
          <span class="input-group-addon">{{t_to}}</span>
          <input type="text" class="input-md form-control" name="rank_end" value="{{ rank_end|default:100 }}">
        </div>
      </div>
      <button type="submit" class="btn btn-default btn-sm">{{t_query}}</button>
    </form>

    <p class="sub-header"></p>
    <div class="table-responsive">
      <div class="panel panel-primary">
        <div class="panel-heading">{{ t_real_rank_info }}
          <span class="pull-right">{{ t_total_number }}<span class="badge">{{ rank.total_count|default:0}}</span></span>
        </div>
        {% if rank.rank_id == 4 %}
        <table class="table table-striped table-condensed">
          <thead>
            <tr>
              <th>{{ t_rank_pos }}</th>
              <th>{{ t_gang_id }}</th>
              <th>{{ t_gang_name }}</th>
              <th>{{ t_gang_level }}</th>
            </tr>
          </thead>
          <tbody>
          {% for k in rank.rank_list %}
          {% with k.rank_val|first as val %}
            <tr>
              <td>{{ k.rank_pos }}</td>
              <td>{{ k.rank_base_info.gang_base_info.gang_id }}</td>
              <td>{{ k.rank_base_info.gang_base_info.gang_name }}</td>
              <td>{{ k.rank_base_info.gang_base_info.gang_level }}</td>
            </tr>
          {% endwith %}
          {% endfor %}
          </tbody>
        </table>
        {% else %}
        <table class="table table-striped table-condensed">
          <thead>
            <tr>
              <th>{{ t_rank_pos }}</th>
              <th>{{ t_player_id }}</th>
              <th>{{ t_player_name }}</th>
              <th>{{ t_recharge_id }}</th>
              <th>{{ t_is_robot }}</th>
            </tr>
          </thead>
          <tbody>
          {% for k in rank.rank_list %}
          {% with k.rank_val|first as val %}
            <tr>
              <td>{{ k.rank_pos }}</td>
              <td>{{ k.rank_base_info.player_base_info.role_id }}</td>
              <td>{{ k.rank_base_info.player_base_info.role_name }}</td>
              <td>{{ k.rank_base_info.player_base_info.cumulate_recharge_id }}</td>
              <td>{{ k.rank_base_info.player_base_info.is_robot }}</td>
            </tr>
          {% endwith %}
          {% endfor %}
          </tbody>
        </table>
        {% endif %}
      </div>
    </div>
  </div>
  <center style='color: #999; padding-top: 20px; font-family: "arial","NSimSun","SimSun","STSong","AR PL SungtiL GB","TW\-Sung","WenQuanYi Bitmap Song"; font-size: 14px; font-weight: bold;'>{{excuse}}</center>
</div>
<script type="text/javascript">
 $(document).ready(function() {
  management.numberOnly("input[name='rank_start']");
  management.numberOnly("input[name='rank_end']");
 });
</script>
{% endblock %}